<a href="https://colab.research.google.com/github/Elisha-Hart/Access-The-String-Using-Slicing-And-Indexing-Assignment/blob/main/Standardize_Data_IRIS_dataset_Scaled_data%2Cetc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [200]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [201]:
data = pd.read_csv("/content/data.zip", encoding_errors = "ignore")

In [202]:
def data_quality_check(data):
  print("Data Head", data.head())
  print("Data Inconsistency Check", data.dtypes)
  print("Data Null Check", data.isnull().sum())
  print("Data Information Check", data.info())
  print("Data Description Check", data.describe())
  print("Data Tail", data.tail())

In [203]:
print(data_quality_check(data))

Data Head     Age Cabin Embarked     Fare                                          Name  \
0  34.5   NaN        Q   7.8292                              Kelly, Mr. James   
1  47.0   NaN        S   7.0000              Wilkes, Mrs. James (Ellen Needs)   
2  62.0   NaN        Q   9.6875                     Myles, Mr. Thomas Francis   
3  27.0   NaN        S   8.6625                              Wirz, Mr. Albert   
4  22.0   NaN        S  12.2875  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   

   Parch  PassengerId  Pclass     Sex  SibSp  Survived   Ticket Title  \
0      0          892       3    male      0       NaN   330911    Mr   
1      0          893       3  female      1       NaN   363272   Mrs   
2      0          894       2    male      0       NaN   240276    Mr   
3      0          895       3    male      0       NaN   315154    Mr   
4      1          896       3  female      1       NaN  3101298   Mrs   

   Family_Size  
0            0  
1            1  
2            

In [204]:
data["Age"].fillna(data["Age"].mean(), inplace = True)
data["Fare"].fillna(data["Fare"].mean(), inplace = True)
data["Cabin"].fillna(data["Cabin"].mode(), inplace = True)

In [205]:
data.isnull().sum()

Age              0
Cabin          326
Embarked         0
Fare             0
Name             0
Parch            0
PassengerId      0
Pclass           0
Sex              0
SibSp            0
Survived       418
Ticket           0
Title            0
Family_Size      0
dtype: int64

In [206]:
### Train Test Split
### Creating Features and Target
X = data.drop(["Survived"], axis = 1)
y = data["Survived"]

In [207]:
X

Age            Cabin Embarked      Fare  \
0    34.5  B57 B59 B63 B66        Q    7.8292   
1    47.0              NaN        S    7.0000   
2    62.0              NaN        Q    9.6875   
3    27.0              NaN        S    8.6625   
4    22.0              NaN        S   12.2875   
..    ...              ...      ...       ...   
413  30.0              NaN        S    8.0500   
414  39.0             C105        C  108.9000   
415  38.5              NaN        S    7.2500   
416  30.0              NaN        S    8.0500   
417   4.0              NaN        C   22.3583   

                                             Name  Parch  PassengerId  Pclass  \
0                                Kelly, Mr. James      0          892       3   
1                Wilkes, Mrs. James (Ellen Needs)      0          893       3   
2                       Myles, Mr. Thomas Francis      0          894       2   
3                                Wirz, Mr. Albert      0          895       3   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)      1          896       3   
..                                            ...    ...          ...     ...   
413                            Spector, Mr. Woolf      0         1305       3   
414                  Oliva y Ocana, Dona. Fermina      0         1306       1   
415                  Saether, Mr. Simon Sivertsen      0         1307       3   
416                           Ware, Mr. Frederick      0         1308       3   
417                      Peter, Master. Michael J      1         1309       3   

        Sex  SibSp              Ticket   Title  Family_Size  
0      male      0              330911      Mr            0  
1    female      1              363272     Mrs            1  
2      male      0              240276      Mr            0  
3      male      0              315154      Mr            0  
4    female      1             3101298     Mrs            2  
..      ...    ...                 ...     ...          ...  
413    male      0           A.5. 3236      Mr            0  
414  female      0            PC 17758     Mrs            0  
415    male      0  SOTON/O.Q. 3101262      Mr            0  
416    male      0              359309      Mr            0  
417    male      1                2668  Master            2  

[418 rows x 13 columns]

In [208]:
y

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
413   NaN
414   NaN
415   NaN
416   NaN
417   NaN
Name: Survived, Length: 418, dtype: float64

In [209]:
X.shape

(418, 13)

In [210]:
from sklearn.model_selection import train_test_split
X_train , x_test , y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [211]:
X_train


Age    Cabin Embarked      Fare  \
207  24.0      NaN        S   10.5000   
108  30.0      NaN        S    8.7125   
389   6.0      NaN        S   21.0750   
184  27.0  B58 B60        C  247.5208   
156  29.0      C97        S  221.7792   
..    ...      ...      ...       ...   
92   27.0      B71        S   52.0000   
84   30.0      NaN        Q   10.7083   
280  23.0      NaN        S    8.6625   
101  27.0      NaN        S   26.0000   
59   36.0      B61        C  262.3750   

                                                  Name  Parch  PassengerId  \
207                       Collett, Mr. Sidney C Stuart      0         1099   
108                   Willer, Mr. Aaron (Abi Weller")"      0         1000   
389                        Palsson, Master. Paul Folke      1         1281   
184  Douglas, Mrs. Frederick Charles (Mary Helene B...      1         1076   
156                                  Bird, Miss. Ellen      0         1048   
..                                                 ...    ...          ...   
92                Davidson, Mrs. Thornton (Orian Hays)      2          984   
84                               Lamb, Mr. John Joseph      0          976   
280                             Oreskovic, Miss. Jelka      0         1172   
101                                 Weisz, Mr. Leopold      0          993   
59                         Chaudanson, Miss. Victorine      0          951   

     Pclass     Sex  SibSp      Ticket   Title  Family_Size  
207       2    male      0       28034      Mr            0  
108       3    male      0        3410      Mr            0  
389       3    male      3      349909  Master            4  
184       1  female      1    PC 17558     Mrs            2  
156       1  female      0    PC 17483    Miss            0  
..      ...     ...    ...         ...     ...          ...  
92        1  female      1  F.C. 12750     Mrs            3  
84        2    male      0      240261      Mr            0  
280       3  female      0      315085    Miss            0  
101       2    male      1      228414      Mr            1  
59        1  female      0    PC 17608    Miss            0  

[334 rows x 13 columns]

In [212]:
X_train.shape

(334, 13)

In [213]:
x_test.shape

(84, 13)

In [214]:
y_train.shape, y_test.shape ### Make sure the numbers match like 334, 84.

((334,), (84,))

In [215]:
data.shape


(418, 14)

In [216]:
from sklearn.preprocessing import StandardScaler

In [217]:
from sklearn.model_selection import train_test_split

In [218]:
from sklearn.impute import SimpleImputer

In [219]:
dataset = pd.read_csv('data.zip')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [220]:
# splitting the dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [221]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
def preprocessing(data):
  # separating numerical and categorical features
  encoder = LabelEncoder()
  scaler = StandardScaler()
  categorical_data, numerical_data = [], []
  for col in data.columns:
    if data[col].dtypes == "object":
      categorical_data.append(col)
      # Encoding the categorical data
      data[col] = encoder.fit_transform(data[col])
    else:
      numerical_data.append(col)
    # Feature Scaling, Applying std or standardization () for all
    scaled_data = scaler.fit_transform(data)

    return scaled_data

In [222]:
X = data.drop(["Survived"], axis = 1)
y = data["Survived"]

In [223]:
from sklearn.datasets import load_iris

In [224]:
from sklearn import preprocessing
data = load_iris()

X_data = data.data
target = data.target

standard = preprocessing.scale(X_data)
print(standard)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [225]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

data = load_iris()
scale = StandardScaler()

X_data = data.data
target = data.target

scaled_data = scale.fit_transform(X_data)
print(scaled_data)



[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [226]:
pd.DataFrame(scaled_data)

0         1         2         3
0   -0.900681  1.019004 -1.340227 -1.315444
1   -1.143017 -0.131979 -1.340227 -1.315444
2   -1.385353  0.328414 -1.397064 -1.315444
3   -1.506521  0.098217 -1.283389 -1.315444
4   -1.021849  1.249201 -1.340227 -1.315444
..        ...       ...       ...       ...
145  1.038005 -0.131979  0.819596  1.448832
146  0.553333 -1.282963  0.705921  0.922303
147  0.795669 -0.131979  0.819596  1.053935
148  0.432165  0.788808  0.933271  1.448832
149  0.068662 -0.131979  0.762758  0.790671

[150 rows x 4 columns]

In [227]:
scaled_data

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [228]:
scaled_df = pd.DataFrame

In [229]:
scaled_df = pd.DataFrame(scaled_data)

In [230]:
X

Age            Cabin Embarked      Fare  \
0    34.5  B57 B59 B63 B66        Q    7.8292   
1    47.0              NaN        S    7.0000   
2    62.0              NaN        Q    9.6875   
3    27.0              NaN        S    8.6625   
4    22.0              NaN        S   12.2875   
..    ...              ...      ...       ...   
413  30.0              NaN        S    8.0500   
414  39.0             C105        C  108.9000   
415  38.5              NaN        S    7.2500   
416  30.0              NaN        S    8.0500   
417   4.0              NaN        C   22.3583   

                                             Name  Parch  PassengerId  Pclass  \
0                                Kelly, Mr. James      0          892       3   
1                Wilkes, Mrs. James (Ellen Needs)      0          893       3   
2                       Myles, Mr. Thomas Francis      0          894       2   
3                                Wirz, Mr. Albert      0          895       3   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)      1          896       3   
..                                            ...    ...          ...     ...   
413                            Spector, Mr. Woolf      0         1305       3   
414                  Oliva y Ocana, Dona. Fermina      0         1306       1   
415                  Saether, Mr. Simon Sivertsen      0         1307       3   
416                           Ware, Mr. Frederick      0         1308       3   
417                      Peter, Master. Michael J      1         1309       3   

        Sex  SibSp              Ticket   Title  Family_Size  
0      male      0              330911      Mr            0  
1    female      1              363272     Mrs            1  
2      male      0              240276      Mr            0  
3      male      0              315154      Mr            0  
4    female      1             3101298     Mrs            2  
..      ...    ...                 ...     ...          ...  
413    male      0           A.5. 3236      Mr            0  
414  female      0            PC 17758     Mrs            0  
415    male      0  SOTON/O.Q. 3101262      Mr            0  
416    male      0              359309      Mr            0  
417    male      1                2668  Master            2  

[418 rows x 13 columns]

In [231]:
y

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
413   NaN
414   NaN
415   NaN
416   NaN
417   NaN
Name: Survived, Length: 418, dtype: float64

In [232]:
y.shape

(418,)

In [233]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [234]:
X_train

Age Cabin Embarked     Fare  \
317  19.0   NaN        S  10.5000   
50   24.0   C31        S  60.0000   
102  30.0   NaN        Q   7.7500   
364  25.0   E50        C  55.4417   
105  28.0   NaN        S  22.5250   
..    ...   ...      ...      ...   
234  39.0   C85        C  71.2833   
205  30.0   NaN        C  25.7417   
401  38.0   NaN        S  21.0000   
48   60.0   D15        C  76.2917   
43   30.0   NaN        S  13.0000   

                                                Name  Parch  PassengerId  \
317                       Rogers, Mr. Reginald Harry      0         1209   
50                          Smith, Mr. Lucien Philip      0          942   
102                               Foley, Mr. William      0          994   
364     Harder, Mrs. George Achilles (Dorothy Annan)      0         1256   
105                        Holthen, Mr. Johan Martin      0          997   
..                                               ...    ...          ...   
234                        Cumings, Mr. John Bradley      0         1126   
205                        Omont, Mr. Alfred Fernand      0         1097   
401                                  Gale, Mr. Harry      0         1293   
48   Bucknell, Mrs. William Robert (Emma Eliza Ward)      0          940   
43             Corbett, Mrs. Walter H (Irene Colvin)      0          935   

     Pclass     Sex  SibSp      Ticket Title  Family_Size  
317       2    male      0       28004    Mr            0  
50        1    male      1       13695    Mr            1  
102       3    male      0      365235    Mr            0  
364       1  female      1       11765   Mrs            1  
105       3    male      0      C 4001    Mr            0  
..      ...     ...    ...         ...   ...          ...  
234       1    male      1    PC 17599    Mr            1  
205       1    male      0  F.C. 12998    Mr            0  
401       2    male      1       28664    Mr            1  
48        1  female      0       11813   Mrs            0  
43        2  female      0      237249   Mrs            0  

[334 rows x 13 columns]

In [235]:
y_train.shape, y_test.shape

((334,), (84,))

In [236]:
y_train.values

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, na

In [237]:
X.shape

(418, 13)

In [238]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()



In [239]:
model.fit

<bound method LogisticRegression.fit of LogisticRegression()>

In [240]:
model

LogisticRegression()

In [241]:
model.predict

<bound method LinearClassifierMixin.predict of LogisticRegression()>

In [242]:
y_test.values

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan])

In [243]:
x_test.values

array([[48.0, 'B57 B59 B63 B66', 'C', ..., 'PC 17608', 'Mrs', 4],
       [30.0, nan, 'S', ..., 'SOTON/O.Q. 3101314', 'Mr', 0],
       [21.0, nan, 'S', ..., '345501', 'Mr', 0],
       ...,
       [30.0, nan, 'S', ..., '345498', 'Mr', 0],
       [28.0, 'C23 C25 C27', 'S', ..., '19950', 'Miss', 5],
       [55.0, 'C39', 'S', ..., '680', 'Mr', 0]], dtype=object)

In [244]:
from sklearn import neighbors, datasets
iris = datasets.load_iris()
X,y = iris.data, iris.target
knn = neighbors.KNeighborsClassifier(n_neighbors=1)
knn.fit(X,y)
print(iris.target_names[knn.predict([[3,5,4,2]])])



['virginica']


In [245]:
from sklearn.linear_model import LinearRegression

X = 30 * np.random.random((20,1))

y = 0.5 * X + 1.0 + np.random.normal(size=X.shape)

model = LinearRegression()
model.fit(X,y)

X_new = np.linspace(0, 30, 100)
y_new = model.predict(X_new[:, np.newaxis])

In [246]:
from sklearn.datasets import load_digits
digits = load_digits()

In [247]:
print(model.predict)

<bound method LinearModel.predict of LinearRegression()>


In [248]:
model.predict
print(X_test)

       Age Cabin Embarked     Fare                            Name  Parch  \
135  24.00   NaN        S   7.8542       Carlsson, Mr. Carl Robert      0   
398  22.00   NaN        S   7.7750  Larsson-Rondberg, Mr. Edvard A      0   
71   21.00   NaN        S   7.8958              Minkoff, Mr. Lazar      0   
36   22.00   NaN        S   8.0500             Roth, Miss. Sarah A      0   
281   0.75   NaN        S  13.7750  Peacock, Master. Alfred Edward      1   
..     ...   ...      ...      ...                             ...    ...   
110  41.00   NaN        C  15.0458        Stanton, Mr. Samuel Ward      0   
200  22.00   NaN        Q  15.5000              Murphy, Miss. Nora      0   
403  17.00   NaN        S  47.1000          Carrau, Mr. Jose Pedro      0   
293  53.00   A34        S  81.8583           Dodge, Dr. Washington      1   
188  22.00   NaN        S  69.5500                 Sage, Miss. Ada      2   

     PassengerId  Pclass     Sex  SibSp              Ticket   Title  \
135 

In [249]:
predicted_data = pd.DataFrame(y_test.values)

In [250]:
predicted_data

0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
..  ..
79 NaN
80 NaN
81 NaN
82 NaN
83 NaN

[84 rows x 1 columns]

In [251]:
predicted_data

0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
..  ..
79 NaN
80 NaN
81 NaN
82 NaN
83 NaN

[84 rows x 1 columns]

In [252]:
predicted_data.reset_index()

index   0
0       0 NaN
1       1 NaN
2       2 NaN
3       3 NaN
4       4 NaN
..    ...  ..
79     79 NaN
80     80 NaN
81     81 NaN
82     82 NaN
83     83 NaN

[84 rows x 2 columns]

In [253]:
predicted_data.reset_index(inplace = True)

In [254]:
columns = ["Actual_Survived", "Predicted_survived"]
predicted_data.columns = columns

In [255]:
predicted_data

Actual_Survived  Predicted_survived
0                 0                 NaN
1                 1                 NaN
2                 2                 NaN
3                 3                 NaN
4                 4                 NaN
..              ...                 ...
79               79                 NaN
80               80                 NaN
81               81                 NaN
82               82                 NaN
83               83                 NaN

[84 rows x 2 columns]

In [256]:
from sklearn.metrics import accuracy_score


In [257]:
acc_of_model = accuracy_score


In [258]:
print("The accuracy of the model is ", acc_of_model)

The accuracy of the model is  <function accuracy_score at 0x7fe5859f5310>


In [259]:
from sklearn.svm import SVC

In [260]:
svc = SVC()




In [261]:
svc.fit = svc

In [262]:
svc.fit

SVC()

In [263]:
print(accuracy_score)

<function accuracy_score at 0x7fe5859f5310>
